"use client"

import React, { createContext, useContext, useState, useCallback, type ReactNode } from 'react'

export type Language = 'en' | 'pt' | 'es' | 'fr' | 'de' | 'hi' | 'ur' | 'pa'

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: 'GB' },
  { code: 'pt', name: 'Português (Portugal)', flag: 'PT' },
  { code: 'es', name: 'Español', flag: 'ES' },
  { code: 'fr', name: 'Français', flag: 'FR' },
  { code: 'de', name: 'Deutsch', flag: 'DE' },
  { code: 'hi', name: 'हिन्दी', flag: 'IN' },
  { code: 'ur', name: 'اردو', flag: 'PK' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: 'IN' },
]

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    shop: 'Shop',
    accessories: 'Accessories',
    brands: 'Brands',
    contact: 'Contact',
    wishlist: 'Wishlist',
    cart: 'Cart',
    search: 'Search products...',
    allCategories: 'All Categories',
    specialBrands: 'Special Brands',
    featuredProducts: 'Featured Products',
    newArrivals: 'New Arrivals',
    bestSellers: 'Best Sellers',
    addToCart: 'Add to Cart',
    addToWishlist: 'Add to Wishlist',
    viewDetails: 'View Details',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    emptyCart: 'Your cart is empty',
    emptyWishlist: 'Your wishlist is empty',
    help: 'Help',
    support: 'Support',
    callUs: 'Call Us',
    myDashboard: 'My Dashboard',
    login: 'Login',
    logout: 'Log Out',
    myAccount: 'My Account',
    notifications: 'Notifications',
    accountSettings: 'Account Settings',
    freeReturn: 'Free Return',
    freeReturnDesc: '30 days money back guarantee!',
    freeShipping: 'Free Shipping',
    freeShippingDesc: 'Free shipping on all orders',
    support247: 'Support 24/7',
    support247Desc: 'We support online 24 hrs a day',
    giftCard: 'Receive Gift Card',
    giftCardDesc: 'Receive gift on orders over $50',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'We value your security',
    onlineService: 'Online Service',
    onlineServiceDesc: 'Free return products in 30 days',
    getInTouch: 'Get in Touch',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourPhone: 'Your Phone',
    subject: 'Subject',
    message: 'Message',
    remove: 'Remove',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    calculated: 'Calculated at checkout',
    iphoneParts: 'iPhone Parts',
    samsungParts: 'Samsung Parts',
    xiaomiParts: 'Xiaomi Parts',
    oppoRenoParts: 'Oppo Reno Parts',
    realmeParts: 'Realme Parts',
    huaweiParts: 'Huawei Parts',
    onePlusParts: 'OnePlus Parts',
    motorolaParts: 'Motorola Parts',
    alcatelParts: 'Alcatel Parts',
    tclParts: 'TCL Parts',
    zteParts: 'ZTE Parts',
    vivoParts: 'Vivo Parts',
    nokiaParts: 'Nokia Parts',
    googlePixelParts: 'Google Pixel Parts',
    tablets: 'Tablets',
    lgParts: 'LG Parts',
    otherParts: 'Other Parts',
    repairTools: 'Repair Tools',
    shopNow: 'Shop Now',
    discoverMore: 'Discover More',
    newsletter: 'Newsletter',
    newsletterDesc: 'Subscribe to get the latest updates',
    subscribe: 'Subscribe',
    enterEmail: 'Enter your email',
    quickLinks: 'Quick Links',
    aboutUs: 'About Us',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    faq: 'FAQ',
    contactInfo: 'Contact Info',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    followUs: 'Follow Us',
    allRightsReserved: 'All Rights Reserved',
    filterBy: 'Filter By',
    sortBy: 'Sort By',
    priceRange: 'Price Range',
    categories: 'Categories',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    sale: 'Sale',
    new: 'New',
    off: 'Off',
    heroTitle: 'Premium Mobile Parts & Accessories',
    heroSubtitle: 'Your one-stop destination for quality mobile phone parts',
    exploreBrands: 'Explore Brands',
    viewAll: 'View All',
    topCategories: 'Top Categories',
    whyChooseUs: 'Why Choose Us',
    qualityProducts: 'Quality Products',
    qualityProductsDesc: 'All products are tested and verified',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Quick and reliable shipping worldwide',
    expertSupport: 'Expert Support',
    expertSupportDesc: 'Technical support from professionals',
    competitivePrices: 'Competitive Prices',
    competitivePricesDesc: 'Best prices in the market',
    dashboard: 'Dashboard',
    usersInformation: 'Users Information',
    subscriptions: 'Subscriptions',
    paymentApprovals: 'Payment Approvals',
  },
  pt: {
    home: 'Início',
    shop: 'Loja',
    accessories: 'Acessórios',
    brands: 'Marcas',
    contact: 'Contacto',
    wishlist: 'Lista de Desejos',
    cart: 'Carrinho',
    search: 'Pesquisar produtos...',
    allCategories: 'Todas as Categorias',
    specialBrands: 'Marcas Especiais',
    featuredProducts: 'Produtos em Destaque',
    newArrivals: 'Novidades',
    bestSellers: 'Mais Vendidos',
    addToCart: 'Adicionar ao Carrinho',
    addToWishlist: 'Adicionar à Lista de Desejos',
    viewDetails: 'Ver Detalhes',
    price: 'Preço',
    quantity: 'Quantidade',
    total: 'Total',
    checkout: 'Finalizar Compra',
    continueShopping: 'Continuar Comprando',
    emptyCart: 'O seu carrinho está vazio',
    emptyWishlist: 'A sua lista de desejos está vazia',
    help: 'Ajuda',
    support: 'Suporte',
    callUs: 'Ligue-nos',
    myDashboard: 'Meu Painel',
    login: 'Entrar',
    logout: 'Sair',
    myAccount: 'Minha Conta',
    notifications: 'Notificações',
    accountSettings: 'Configurações da Conta',
    freeReturn: 'Devolução Grátis',
    freeReturnDesc: 'Garantia de devolução de 30 dias!',
    freeShipping: 'Envio Grátis',
    freeShippingDesc: 'Envio gratuito em todas as encomendas',
    support247: 'Suporte 24/7',
    support247Desc: 'Suporte online 24 horas por dia',
    giftCard: 'Receba Cartão Presente',
    giftCardDesc: 'Receba presente em compras acima de 50€',
    securePayment: 'Pagamento Seguro',
    securePaymentDesc: 'Valorizamos a sua segurança',
    onlineService: 'Serviço Online',
    onlineServiceDesc: 'Devolução grátis em 30 dias',
    getInTouch: 'Entre em Contacto',
    sendMessage: 'Enviar Mensagem',
    yourName: 'O Seu Nome',
    yourEmail: 'O Seu Email',
    yourPhone: 'O Seu Telefone',
    subject: 'Assunto',
    message: 'Mensagem',
    remove: 'Remover',
    subtotal: 'Subtotal',
    shipping: 'Envio',
    calculated: 'Calculado no checkout',
    iphoneParts: 'Peças iPhone',
    samsungParts: 'Peças Samsung',
    xiaomiParts: 'Peças Xiaomi',
    oppoRenoParts: 'Peças Oppo Reno',
    realmeParts: 'Peças Realme',
    huaweiParts: 'Peças Huawei',
    onePlusParts: 'Peças OnePlus',
    motorolaParts: 'Peças Motorola',
    alcatelParts: 'Peças Alcatel',
    tclParts: 'Peças TCL',
    zteParts: 'Peças ZTE',
    vivoParts: 'Peças Vivo',
    nokiaParts: 'Peças Nokia',
    googlePixelParts: 'Peças Google Pixel',
    tablets: 'Tablets',
    lgParts: 'Peças LG',
    otherParts: 'Outras Peças',
    repairTools: 'Ferramentas de Reparo',
    shopNow: 'Comprar Agora',
    discoverMore: 'Descobrir Mais',
    newsletter: 'Boletim Informativo',
    newsletterDesc: 'Subscreva para receber as últimas atualizações',
    subscribe: 'Subscrever',
    enterEmail: 'Introduza o seu email',
    quickLinks: 'Links Rápidos',
    aboutUs: 'Sobre Nós',
    privacyPolicy: 'Política de Privacidade',
    termsConditions: 'Termos e Condições',
    faq: 'Perguntas Frequentes',
    contactInfo: 'Informação de Contacto',
    address: 'Morada',
    phone: 'Telefone',
    email: 'Email',
    followUs: 'Siga-nos',
    allRightsReserved: 'Todos os Direitos Reservados',
    filterBy: 'Filtrar Por',
    sortBy: 'Ordenar Por',
    priceRange: 'Gama de Preços',
    categories: 'Categorias',
    inStock: 'Em Stock',
    outOfStock: 'Esgotado',
    sale: 'Promoção',
    new: 'Novo',
    off: 'Desconto',
    heroTitle: 'Peças e Acessórios Premium para Telemóveis',
    heroSubtitle: 'O seu destino único para peças de telemóvel de qualidade',
    exploreBrands: 'Explorar Marcas',
    viewAll: 'Ver Todos',
    topCategories: 'Categorias Principais',
    whyChooseUs: 'Porquê Escolher-nos',
    qualityProducts: 'Produtos de Qualidade',
    qualityProductsDesc: 'Todos os produtos são testados e verificados',
    fastDelivery: 'Entrega Rápida',
    fastDeliveryDesc: 'Envio rápido e fiável para todo o mundo',
    expertSupport: 'Suporte Especializado',
    expertSupportDesc: 'Suporte técnico de profissionais',
    competitivePrices: 'Preços Competitivos',
    competitivePricesDesc: 'Os melhores preços do mercado',
    dashboard: 'Painel',
    usersInformation: 'Informação de Utilizadores',
    subscriptions: 'Subscrições',
    paymentApprovals: 'Aprovações de Pagamento',
  },
  es: {
    home: 'Inicio',
    shop: 'Tienda',
    accessories: 'Accesorios',
    brands: 'Marcas',
    contact: 'Contacto',
    wishlist: 'Lista de Deseos',
    cart: 'Carrito',
    search: 'Buscar productos...',
    allCategories: 'Todas las Categorías',
    specialBrands: 'Marcas Especiales',
    featuredProducts: 'Productos Destacados',
    newArrivals: 'Novedades',
    bestSellers: 'Más Vendidos',
    addToCart: 'Añadir al Carrito',
    addToWishlist: 'Añadir a Lista de Deseos',
    viewDetails: 'Ver Detalles',
    price: 'Precio',
    quantity: 'Cantidad',
    total: 'Total',
    checkout: 'Finalizar Compra',
    continueShopping: 'Seguir Comprando',
    emptyCart: 'Tu carrito está vacío',
    emptyWishlist: 'Tu lista de deseos está vacía',
    help: 'Ayuda',
    support: 'Soporte',
    callUs: 'Llámanos',
    myDashboard: 'Mi Panel',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    myAccount: 'Mi Cuenta',
    notifications: 'Notificaciones',
    accountSettings: 'Configuración de Cuenta',
    freeReturn: 'Devolución Gratis',
    freeReturnDesc: '¡Garantía de devolución de 30 días!',
    freeShipping: 'Envío Gratis',
    freeShippingDesc: 'Envío gratuito en todos los pedidos',
    support247: 'Soporte 24/7',
    support247Desc: 'Soporte en línea 24 horas al día',
    giftCard: 'Reciba Tarjeta Regalo',
    giftCardDesc: 'Reciba regalo en pedidos superiores a 50€',
    securePayment: 'Pago Seguro',
    securePaymentDesc: 'Valoramos tu seguridad',
    onlineService: 'Servicio Online',
    onlineServiceDesc: 'Devolución gratis en 30 días',
    getInTouch: 'Ponte en Contacto',
    sendMessage: 'Enviar Mensaje',
    yourName: 'Tu Nombre',
    yourEmail: 'Tu Email',
    yourPhone: 'Tu Teléfono',
    subject: 'Asunto',
    message: 'Mensaje',
    remove: 'Eliminar',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    calculated: 'Calculado en el checkout',
    iphoneParts: 'Piezas iPhone',
    samsungParts: 'Piezas Samsung',
    xiaomiParts: 'Piezas Xiaomi',
    oppoRenoParts: 'Piezas Oppo Reno',
    realmeParts: 'Piezas Realme',
    huaweiParts: 'Piezas Huawei',
    onePlusParts: 'Piezas OnePlus',
    motorolaParts: 'Piezas Motorola',
    alcatelParts: 'Piezas Alcatel',
    tclParts: 'Piezas TCL',
    zteParts: 'Piezas ZTE',
    vivoParts: 'Piezas Vivo',
    nokiaParts: 'Piezas Nokia',
    googlePixelParts: 'Piezas Google Pixel',
    tablets: 'Tablets',
    lgParts: 'Piezas LG',
    otherParts: 'Otras Piezas',
    repairTools: 'Herramientas de Reparación',
    shopNow: 'Comprar Ahora',
    discoverMore: 'Descubrir Más',
    newsletter: 'Boletín',
    newsletterDesc: 'Suscríbete para recibir las últimas actualizaciones',
    subscribe: 'Suscribirse',
    enterEmail: 'Introduce tu email',
    quickLinks: 'Enlaces Rápidos',
    aboutUs: 'Sobre Nosotros',
    privacyPolicy: 'Política de Privacidad',
    termsConditions: 'Términos y Condiciones',
    faq: 'Preguntas Frecuentes',
    contactInfo: 'Información de Contacto',
    address: 'Dirección',
    phone: 'Teléfono',
    email: 'Email',
    followUs: 'Síguenos',
    allRightsReserved: 'Todos los Derechos Reservados',
    filterBy: 'Filtrar Por',
    sortBy: 'Ordenar Por',
    priceRange: 'Rango de Precios',
    categories: 'Categorías',
    inStock: 'En Stock',
    outOfStock: 'Agotado',
    sale: 'Oferta',
    new: 'Nuevo',
    off: 'Descuento',
    heroTitle: 'Piezas y Accesorios Premium para Móviles',
    heroSubtitle: 'Tu destino único para piezas de móvil de calidad',
    exploreBrands: 'Explorar Marcas',
    viewAll: 'Ver Todo',
    topCategories: 'Categorías Principales',
    whyChooseUs: 'Por Qué Elegirnos',
    qualityProducts: 'Productos de Calidad',
    qualityProductsDesc: 'Todos los productos son probados y verificados',
    fastDelivery: 'Entrega Rápida',
    fastDeliveryDesc: 'Envío rápido y confiable a todo el mundo',
    expertSupport: 'Soporte Experto',
    expertSupportDesc: 'Soporte técnico de profesionales',
    competitivePrices: 'Precios Competitivos',
    competitivePricesDesc: 'Los mejores precios del mercado',
    dashboard: 'Panel',
    usersInformation: 'Información de Usuarios',
    subscriptions: 'Suscripciones',
    paymentApprovals: 'Aprobaciones de Pago',
  },
  fr: {
    home: 'Accueil',
    shop: 'Boutique',
    accessories: 'Accessoires',
    brands: 'Marques',
    contact: 'Contact',
    wishlist: 'Liste de Souhaits',
    cart: 'Panier',
    search: 'Rechercher des produits...',
    allCategories: 'Toutes les Catégories',
    specialBrands: 'Marques Spéciales',
    featuredProducts: 'Produits Vedettes',
    newArrivals: 'Nouveautés',
    bestSellers: 'Meilleures Ventes',
    addToCart: 'Ajouter au Panier',
    addToWishlist: 'Ajouter à la Liste de Souhaits',
    viewDetails: 'Voir Détails',
    price: 'Prix',
    quantity: 'Quantité',
    total: 'Total',
    checkout: 'Passer à la Caisse',
    continueShopping: 'Continuer les Achats',
    emptyCart: 'Votre panier est vide',
    emptyWishlist: 'Votre liste de souhaits est vide',
    help: 'Aide',
    support: 'Support',
    callUs: 'Appelez-nous',
    myDashboard: 'Mon Tableau de Bord',
    login: 'Connexion',
    logout: 'Déconnexion',
    myAccount: 'Mon Compte',
    notifications: 'Notifications',
    accountSettings: 'Paramètres du Compte',
    freeReturn: 'Retour Gratuit',
    freeReturnDesc: 'Garantie de remboursement de 30 jours!',
    freeShipping: 'Livraison Gratuite',
    freeShippingDesc: 'Livraison gratuite sur toutes les commandes',
    support247: 'Support 24/7',
    support247Desc: 'Nous supportons en ligne 24h/24',
    giftCard: 'Recevez une Carte Cadeau',
    giftCardDesc: 'Recevez un cadeau sur les commandes de plus de 50€',
    securePayment: 'Paiement Sécurisé',
    securePaymentDesc: 'Nous valorisons votre sécurité',
    onlineService: 'Service en Ligne',
    onlineServiceDesc: 'Retour gratuit sous 30 jours',
    getInTouch: 'Contactez-nous',
    sendMessage: 'Envoyer le Message',
    yourName: 'Votre Nom',
    yourEmail: 'Votre Email',
    yourPhone: 'Votre Téléphone',
    subject: 'Sujet',
    message: 'Message',
    remove: 'Supprimer',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    calculated: 'Calculé à la caisse',
    iphoneParts: 'Pièces iPhone',
    samsungParts: 'Pièces Samsung',
    xiaomiParts: 'Pièces Xiaomi',
    oppoRenoParts: 'Pièces Oppo Reno',
    realmeParts: 'Pièces Realme',
    huaweiParts: 'Pièces Huawei',
    onePlusParts: 'Pièces OnePlus',
    motorolaParts: 'Pièces Motorola',
    alcatelParts: 'Pièces Alcatel',
    tclParts: 'Pièces TCL',
    zteParts: 'Pièces ZTE',
    vivoParts: 'Pièces Vivo',
    nokiaParts: 'Pièces Nokia',
    googlePixelParts: 'Pièces Google Pixel',
    tablets: 'Tablettes',
    lgParts: 'Pièces LG',
    otherParts: 'Autres Pièces',
    repairTools: 'Outils de Réparation',
    shopNow: 'Acheter Maintenant',
    discoverMore: 'Découvrir Plus',
    newsletter: 'Newsletter',
    newsletterDesc: 'Abonnez-vous pour recevoir les dernières mises à jour',
    subscribe: "S'abonner",
    enterEmail: 'Entrez votre email',
    quickLinks: 'Liens Rapides',
    aboutUs: 'À Propos',
    privacyPolicy: 'Politique de Confidentialité',
    termsConditions: 'Termes et Conditions',
    faq: 'FAQ',
    contactInfo: 'Informations de Contact',
    address: 'Adresse',
    phone: 'Téléphone',
    email: 'Email',
    followUs: 'Suivez-nous',
    allRightsReserved: 'Tous Droits Réservés',
    filterBy: 'Filtrer Par',
    sortBy: 'Trier Par',
    priceRange: 'Gamme de Prix',
    categories: 'Catégories',
    inStock: 'En Stock',
    outOfStock: 'Rupture de Stock',
    sale: 'Solde',
    new: 'Nouveau',
    off: 'Réduction',
    heroTitle: 'Pièces et Accessoires Premium pour Mobiles',
    heroSubtitle: 'Votre destination unique pour des pièces de mobile de qualité',
    exploreBrands: 'Explorer les Marques',
    viewAll: 'Voir Tout',
    topCategories: 'Catégories Principales',
    whyChooseUs: 'Pourquoi Nous Choisir',
    qualityProducts: 'Produits de Qualité',
    qualityProductsDesc: 'Tous les produits sont testés et vérifiés',
    fastDelivery: 'Livraison Rapide',
    fastDeliveryDesc: 'Expédition rapide et fiable dans le monde entier',
    expertSupport: 'Support Expert',
    expertSupportDesc: 'Support technique par des professionnels',
    competitivePrices: 'Prix Compétitifs',
    competitivePricesDesc: 'Les meilleurs prix du marché',
    dashboard: 'Tableau de Bord',
    usersInformation: 'Informations Utilisateurs',
    subscriptions: 'Abonnements',
    paymentApprovals: 'Approbations de Paiement',
  },
  de: {
    home: 'Startseite',
    shop: 'Shop',
    accessories: 'Zubehör',
    brands: 'Marken',
    contact: 'Kontakt',
    wishlist: 'Wunschliste',
    cart: 'Warenkorb',
    search: 'Produkte suchen...',
    allCategories: 'Alle Kategorien',
    specialBrands: 'Spezielle Marken',
    featuredProducts: 'Ausgewählte Produkte',
    newArrivals: 'Neuheiten',
    bestSellers: 'Bestseller',
    addToCart: 'In den Warenkorb',
    addToWishlist: 'Zur Wunschliste hinzufügen',
    viewDetails: 'Details anzeigen',
    price: 'Preis',
    quantity: 'Menge',
    total: 'Gesamt',
    checkout: 'Zur Kasse',
    continueShopping: 'Weiter einkaufen',
    emptyCart: 'Ihr Warenkorb ist leer',
    emptyWishlist: 'Ihre Wunschliste ist leer',
    help: 'Hilfe',
    support: 'Support',
    callUs: 'Rufen Sie uns an',
    myDashboard: 'Mein Dashboard',
    login: 'Anmelden',
    logout: 'Abmelden',
    myAccount: 'Mein Konto',
    notifications: 'Benachrichtigungen',
    accountSettings: 'Kontoeinstellungen',
    freeReturn: 'Kostenlose Rückgabe',
    freeReturnDesc: '30 Tage Geld-zurück-Garantie!',
    freeShipping: 'Kostenloser Versand',
    freeShippingDesc: 'Kostenloser Versand bei allen Bestellungen',
    support247: 'Support 24/7',
    support247Desc: 'Wir unterstützen Sie online rund um die Uhr',
    giftCard: 'Geschenkkarte erhalten',
    giftCardDesc: 'Erhalten Sie ein Geschenk bei Bestellungen über 50€',
    securePayment: 'Sichere Zahlung',
    securePaymentDesc: 'Wir schätzen Ihre Sicherheit',
    onlineService: 'Online-Service',
    onlineServiceDesc: 'Kostenlose Rückgabe innerhalb von 30 Tagen',
    getInTouch: 'Kontaktieren Sie uns',
    sendMessage: 'Nachricht senden',
    yourName: 'Ihr Name',
    yourEmail: 'Ihre E-Mail',
    yourPhone: 'Ihre Telefonnummer',
    subject: 'Betreff',
    message: 'Nachricht',
    remove: 'Entfernen',
    subtotal: 'Zwischensumme',
    shipping: 'Versand',
    calculated: 'Wird an der Kasse berechnet',
    iphoneParts: 'iPhone Teile',
    samsungParts: 'Samsung Teile',
    xiaomiParts: 'Xiaomi Teile',
    oppoRenoParts: 'Oppo Reno Teile',
    realmeParts: 'Realme Teile',
    huaweiParts: 'Huawei Teile',
    onePlusParts: 'OnePlus Teile',
    motorolaParts: 'Motorola Teile',
    alcatelParts: 'Alcatel Teile',
    tclParts: 'TCL Teile',
    zteParts: 'ZTE Teile',
    vivoParts: 'Vivo Teile',
    nokiaParts: 'Nokia Teile',
    googlePixelParts: 'Google Pixel Teile',
    tablets: 'Tablets',
    lgParts: 'LG Teile',
    otherParts: 'Andere Teile',
    repairTools: 'Reparaturwerkzeuge',
    shopNow: 'Jetzt einkaufen',
    discoverMore: 'Mehr entdecken',
    newsletter: 'Newsletter',
    newsletterDesc: 'Abonnieren Sie für die neuesten Updates',
    subscribe: 'Abonnieren',
    enterEmail: 'Geben Sie Ihre E-Mail ein',
    quickLinks: 'Schnelllinks',
    aboutUs: 'Über uns',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsConditions: 'Allgemeine Geschäftsbedingungen',
    faq: 'FAQ',
    contactInfo: 'Kontaktinformationen',
    address: 'Adresse',
    phone: 'Telefon',
    email: 'E-Mail',
    followUs: 'Folgen Sie uns',
    allRightsReserved: 'Alle Rechte vorbehalten',
    filterBy: 'Filtern nach',
    sortBy: 'Sortieren nach',
    priceRange: 'Preisbereich',
    categories: 'Kategorien',
    inStock: 'Auf Lager',
    outOfStock: 'Ausverkauft',
    sale: 'Angebot',
    new: 'Neu',
    off: 'Rabatt',
    heroTitle: 'Premium Handy-Teile & Zubehör',
    heroSubtitle: 'Ihr einziges Ziel für hochwertige Handy-Teile',
    exploreBrands: 'Marken erkunden',
    viewAll: 'Alle anzeigen',
    topCategories: 'Top-Kategorien',
    whyChooseUs: 'Warum uns wählen',
    qualityProducts: 'Qualitätsprodukte',
    qualityProductsDesc: 'Alle Produkte werden getestet und verifiziert',
    fastDelivery: 'Schnelle Lieferung',
    fastDeliveryDesc: 'Schneller und zuverlässiger weltweiter Versand',
    expertSupport: 'Experten-Support',
    expertSupportDesc: 'Technischer Support von Fachleuten',
    competitivePrices: 'Wettbewerbsfähige Preise',
    competitivePricesDesc: 'Die besten Preise auf dem Markt',
    dashboard: 'Dashboard',
    usersInformation: 'Benutzerinformationen',
    subscriptions: 'Abonnements',
    paymentApprovals: 'Zahlungsgenehmigungen',
  },
  hi: {
    home: 'होम',
    shop: 'शॉप',
    accessories: 'एक्सेसरीज',
    brands: 'ब्रांड्स',
    contact: 'संपर्क',
    wishlist: 'विशलिस्ट',
    cart: 'कार्ट',
    search: 'उत्पाद खोजें...',
    allCategories: 'सभी श्रेणियाँ',
    specialBrands: 'विशेष ब्रांड्स',
    featuredProducts: 'विशेष उत्पाद',
    newArrivals: 'नए आगमन',
    bestSellers: 'बेस्ट सेलर्स',
    addToCart: 'कार्ट में जोड़ें',
    addToWishlist: 'विशलिस्ट में जोड़ें',
    viewDetails: 'विवरण देखें',
    price: 'मूल्य',
    quantity: 'मात्रा',
    total: 'कुल',
    checkout: 'चेकआउट',
    continueShopping: 'खरीदारी जारी रखें',
    emptyCart: 'आपका कार्ट खाली है',
    emptyWishlist: 'आपकी विशलिस्ट खाली है',
    help: 'मदद',
    support: 'सहायता',
    callUs: 'हमें कॉल करें',
    myDashboard: 'मेरा डैशबोर्ड',
    login: 'लॉगिन',
    logout: 'लॉग आउट',
    myAccount: 'मेरा खाता',
    notifications: 'सूचनाएं',
    accountSettings: 'खाता सेटिंग्स',
    freeReturn: 'मुफ्त रिटर्न',
    freeReturnDesc: '30 दिन की मनी बैक गारंटी!',
    freeShipping: 'मुफ्त शिपिंग',
    freeShippingDesc: 'सभी ऑर्डर पर मुफ्त शिपिंग',
    support247: '24/7 सहायता',
    support247Desc: 'हम 24 घंटे ऑनलाइन सहायता करते हैं',
    giftCard: 'गिफ्ट कार्ड प्राप्त करें',
    giftCardDesc: '$50 से अधिक के ऑर्डर पर गिफ्ट प्राप्त करें',
    securePayment: 'सुरक्षित भुगतान',
    securePaymentDesc: 'हम आपकी सुरक्षा को महत्व देते हैं',
    onlineService: 'ऑनलाइन सेवा',
    onlineServiceDesc: '30 दिनों में मुफ्त रिटर्न',
    getInTouch: 'संपर्क करें',
    sendMessage: 'संदेश भेजें',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    yourPhone: 'आपका फोन',
    subject: 'विषय',
    message: 'संदेश',
    remove: 'हटाएं',
    subtotal: 'उप-योग',
    shipping: 'शिपिंग',
    calculated: 'चेकआउट पर गणना',
    iphoneParts: 'iPhone पार्ट्स',
    samsungParts: 'Samsung पार्ट्स',
    xiaomiParts: 'Xiaomi पार्ट्स',
    oppoRenoParts: 'Oppo Reno पार्ट्स',
    realmeParts: 'Realme पार्ट्स',
    huaweiParts: 'Huawei पार्ट्स',
    onePlusParts: 'OnePlus पार्ट्स',
    motorolaParts: 'Motorola पार्ट्स',
    alcatelParts: 'Alcatel पार्ट्स',
    tclParts: 'TCL पार्ट्स',
    zteParts: 'ZTE पार्ट्स',
    vivoParts: 'Vivo पार्ट्स',
    nokiaParts: 'Nokia पार्ट्स',
    googlePixelParts: 'Google Pixel पार्ट्स',
    tablets: 'टैबलेट्स',
    lgParts: 'LG पार्ट्स',
    otherParts: 'अन्य पार्ट्स',
    repairTools: 'रिपेयर टूल्स',
    shopNow: 'अभी खरीदें',
    discoverMore: 'और जानें',
    newsletter: 'न्यूज़लेटर',
    newsletterDesc: 'नवीनतम अपडेट के लिए सब्सक्राइब करें',
    subscribe: 'सब्सक्राइब',
    enterEmail: 'अपना ईमेल दर्ज करें',
    quickLinks: 'त्वरित लिंक',
    aboutUs: 'हमारे बारे में',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम और शर्तें',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    contactInfo: 'संपर्क जानकारी',
    address: 'पता',
    phone: 'फोन',
    email: 'ईमेल',
    followUs: 'हमें फॉलो करें',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    filterBy: 'फ़िल्टर करें',
    sortBy: 'सॉर्ट करें',
    priceRange: 'मूल्य सीमा',
    categories: 'श्रेणियाँ',
    inStock: 'स्टॉक में',
    outOfStock: 'स्टॉक में नहीं',
    sale: 'सेल',
    new: 'नया',
    off: 'छूट',
    heroTitle: 'प्रीमियम मोबाइल पार्ट्स और एक्सेसरीज',
    heroSubtitle: 'गुणवत्ता वाले मोबाइल पार्ट्स के लिए आपका एकमात्र गंतव्य',
    exploreBrands: 'ब्रांड्स देखें',
    viewAll: 'सभी देखें',
    topCategories: 'शीर्ष श्रेणियाँ',
    whyChooseUs: 'हमें क्यों चुनें',
    qualityProducts: 'गुणवत्ता उत्पाद',
    qualityProductsDesc: 'सभी उत्पाद परीक्षित और सत्यापित हैं',
    fastDelivery: 'तेज़ डिलीवरी',
    fastDeliveryDesc: 'विश्वभर में तेज़ और विश्वसनीय शिपिंग',
    expertSupport: 'विशेषज्ञ सहायता',
    expertSupportDesc: 'पेशेवरों से तकनीकी सहायता',
    competitivePrices: 'प्रतिस्पर्धी कीमतें',
    competitivePricesDesc: 'बाजार में सर्वोत्तम कीमतें',
    dashboard: 'डैशबोर्ड',
    usersInformation: 'उपयोगकर्ता जानकारी',
    subscriptions: 'सदस्यताएं',
    paymentApprovals: 'भुगतान अनुमोदन',
  },
  ur: {
    home: 'ہوم',
    shop: 'شاپ',
    accessories: 'لوازمات',
    brands: 'برانڈز',
    contact: 'رابطہ',
    wishlist: 'خواہشات کی فہرست',
    cart: 'کارٹ',
    search: 'مصنوعات تلاش کریں...',
    allCategories: 'تمام اقسام',
    specialBrands: 'خاص برانڈز',
    featuredProducts: 'نمایاں مصنوعات',
    newArrivals: 'نئی آمد',
    bestSellers: 'بہترین فروخت',
    addToCart: 'کارٹ میں شامل کریں',
    addToWishlist: 'خواہشات کی فہرست میں شامل کریں',
    viewDetails: 'تفصیلات دیکھیں',
    price: 'قیمت',
    quantity: 'مقدار',
    total: 'کل',
    checkout: 'چیک آؤٹ',
    continueShopping: 'خریداری جاری رکھیں',
    emptyCart: 'آپ کا کارٹ خالی ہے',
    emptyWishlist: 'آپ کی خواہشات کی فہرست خالی ہے',
    help: 'مدد',
    support: 'سپورٹ',
    callUs: 'ہمیں کال کریں',
    myDashboard: 'میرا ڈیش بورڈ',
    login: 'لاگ ان',
    logout: 'لاگ آؤٹ',
    myAccount: 'میرا اکاؤنٹ',
    notifications: 'اطلاعات',
    accountSettings: 'اکاؤنٹ کی ترتیبات',
    freeReturn: 'مفت واپسی',
    freeReturnDesc: '30 دن کی رقم واپسی کی گارنٹی!',
    freeShipping: 'مفت شپنگ',
    freeShippingDesc: 'تمام آرڈرز پر مفت شپنگ',
    support247: '24/7 سپورٹ',
    support247Desc: 'ہم 24 گھنٹے آن لائن سپورٹ کرتے ہیں',
    giftCard: 'گفٹ کارڈ حاصل کریں',
    giftCardDesc: '$50 سے زیادہ کے آرڈر پر گفٹ حاصل کریں',
    securePayment: 'محفوظ ادائیگی',
    securePaymentDesc: 'ہم آپ کی سیکیورٹی کی قدر کرتے ہیں',
    onlineService: 'آن لائن سروس',
    onlineServiceDesc: '30 دنوں میں مفت واپسی',
    getInTouch: 'رابطہ کریں',
    sendMessage: 'پیغام بھیجیں',
    yourName: 'آپ کا نام',
    yourEmail: 'آپ کا ای میل',
    yourPhone: 'آپ کا فون',
    subject: 'موضوع',
    message: 'پیغام',
    remove: 'ہٹائیں',
    subtotal: 'ذیلی کل',
    shipping: 'شپنگ',
    calculated: 'چیک آؤٹ پر حساب',
    iphoneParts: 'آئی فون پارٹس',
    samsungParts: 'سام سنگ پارٹس',
    xiaomiParts: 'ژیاؤمی پارٹس',
    oppoRenoParts: 'اوپو رینو پارٹس',
    realmeParts: 'ریئلمی پارٹس',
    huaweiParts: 'ہواوے پارٹس',
    onePlusParts: 'ون پلس پارٹس',
    motorolaParts: 'موٹورولا پارٹس',
    alcatelParts: 'الکاٹیل پارٹس',
    tclParts: 'ٹی سی ایل پارٹس',
    zteParts: 'زیڈ ٹی ای پارٹس',
    vivoParts: 'ویوو پارٹس',
    nokiaParts: 'نوکیا پارٹس',
    googlePixelParts: 'گوگل پکسل پارٹس',
    tablets: 'ٹیبلیٹس',
    lgParts: 'ایل جی پارٹس',
    otherParts: 'دیگر پارٹس',
    repairTools: 'مرمت کے آلات',
    shopNow: 'ابھی خریدیں',
    discoverMore: 'مزید دریافت کریں',
    newsletter: 'نیوز لیٹر',
    newsletterDesc: 'تازہ ترین اپڈیٹس کے لیے سبسکرائب کریں',
    subscribe: 'سبسکرائب',
    enterEmail: 'اپنا ای میل درج کریں',
    quickLinks: 'فوری لنکس',
    aboutUs: 'ہمارے بارے میں',
    privacyPolicy: 'رازداری کی پالیسی',
    termsConditions: 'شرائط و ضوابط',
    faq: 'اکثر پوچھے گئے سوالات',
    contactInfo: 'رابطہ کی معلومات',
    address: 'پتہ',
    phone: 'فون',
    email: 'ای میل',
    followUs: 'ہمیں فالو کریں',
    allRightsReserved: 'جملہ حقوق محفوظ ہیں',
    filterBy: 'فلٹر کریں',
    sortBy: 'ترتیب دیں',
    priceRange: 'قیمت کی حد',
    categories: 'اقسام',
    inStock: 'اسٹاک میں',
    outOfStock: 'اسٹاک میں نہیں',
    sale: 'سیل',
    new: 'نیا',
    off: 'چھوٹ',
    heroTitle: 'پریمیم موبائل پارٹس اور لوازمات',
    heroSubtitle: 'معیاری موبائل پارٹس کے لیے آپ کی واحد منزل',
    exploreBrands: 'برانڈز دیکھیں',
    viewAll: 'سب دیکھیں',
    topCategories: 'اعلیٰ اقسام',
    whyChooseUs: 'ہمیں کیوں چنیں',
    qualityProducts: 'معیاری مصنوعات',
    qualityProductsDesc: 'تمام مصنوعات ٹیسٹ اور تصدیق شدہ ہیں',
    fastDelivery: 'تیز ڈیلیوری',
    fastDeliveryDesc: 'دنیا بھر میں تیز اور قابل اعتماد شپنگ',
    expertSupport: 'ماہر سپورٹ',
    expertSupportDesc: 'پیشہ ور افراد سے تکنیکی مدد',
    competitivePrices: 'مسابقتی قیمتیں',
    competitivePricesDesc: 'مارکیٹ میں بہترین قیمتیں',
    dashboard: 'ڈیش بورڈ',
    usersInformation: 'صارفین کی معلومات',
    subscriptions: 'سبسکرپشنز',
    paymentApprovals: 'ادائیگی کی منظوریاں',
  },
  pa: {
    home: 'ਹੋਮ',
    shop: 'ਸ਼ਾਪ',
    accessories: 'ਸਹਾਇਕ ਉਪਕਰਣ',
    brands: 'ਬ੍ਰਾਂਡ',
    contact: 'ਸੰਪਰਕ',
    wishlist: 'ਇੱਛਾ ਸੂਚੀ',
    cart: 'ਕਾਰਟ',
    search: 'ਉਤਪਾਦ ਖੋਜੋ...',
    allCategories: 'ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    specialBrands: 'ਵਿਸ਼ੇਸ਼ ਬ੍ਰਾਂਡ',
    featuredProducts: 'ਵਿਸ਼ੇਸ਼ ਉਤਪਾਦ',
    newArrivals: 'ਨਵੇਂ ਆਏ',
    bestSellers: 'ਬੈਸਟ ਸੇਲਰ',
    addToCart: 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    addToWishlist: 'ਇੱਛਾ ਸੂਚੀ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    viewDetails: 'ਵੇਰਵੇ ਦੇਖੋ',
    price: 'ਕੀਮਤ',
    quantity: 'ਮਾਤਰਾ',
    total: 'ਕੁੱਲ',
    checkout: 'ਚੈੱਕਆਊਟ',
    continueShopping: 'ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ',
    emptyCart: 'ਤੁਹਾਡਾ ਕਾਰਟ ਖਾਲੀ ਹੈ',
    emptyWishlist: 'ਤੁਹਾਡੀ ਇੱਛਾ ਸੂਚੀ ਖਾਲੀ ਹੈ',
    help: 'ਮਦਦ',
    support: 'ਸਹਾਇਤਾ',
    callUs: 'ਸਾਨੂੰ ਕਾਲ ਕਰੋ',
    myDashboard: 'ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ',
    login: 'ਲੌਗਇਨ',
    logout: 'ਲੌਗ ਆਊਟ',
    myAccount: 'ਮੇਰਾ ਖਾਤਾ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    accountSettings: 'ਖਾਤਾ ਸੈਟਿੰਗਾਂ',
    freeReturn: 'ਮੁਫ਼ਤ ਵਾਪਸੀ',
    freeReturnDesc: '30 ਦਿਨਾਂ ਦੀ ਪੈਸੇ ਵਾਪਸ ਗਾਰੰਟੀ!',
    freeShipping: 'ਮੁਫ਼ਤ ਸ਼ਿਪਿੰਗ',
    freeShippingDesc: 'ਸਾਰੇ ਆਰਡਰਾਂ ਤੇ ਮੁਫ਼ਤ ਸ਼ਿਪਿੰਗ',
    support247: '24/7 ਸਹਾਇਤਾ',
    support247Desc: 'ਅਸੀਂ 24 ਘੰਟੇ ਔਨਲਾਈਨ ਸਹਾਇਤਾ ਕਰਦੇ ਹਾਂ',
    giftCard: 'ਗਿਫਟ ਕਾਰਡ ਪ੍ਰਾਪਤ ਕਰੋ',
    giftCardDesc: '$50 ਤੋਂ ਵੱਧ ਦੇ ਆਰਡਰ ਤੇ ਗਿਫਟ ਪ੍ਰਾਪਤ ਕਰੋ',
    securePayment: 'ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ',
    securePaymentDesc: 'ਅਸੀਂ ਤੁਹਾਡੀ ਸੁਰੱਖਿਆ ਦੀ ਕਦਰ ਕਰਦੇ ਹਾਂ',
    onlineService: 'ਔਨਲਾਈਨ ਸੇਵਾ',
    onlineServiceDesc: '30 ਦਿਨਾਂ ਵਿੱਚ ਮੁਫ਼ਤ ਵਾਪਸੀ',
    getInTouch: 'ਸੰਪਰਕ ਕਰੋ',
    sendMessage: 'ਸੁਨੇਹਾ ਭੇਜੋ',
    yourName: 'ਤੁਹਾਡਾ ਨਾਮ',
    yourEmail: 'ਤੁਹਾਡੀ ਈਮੇਲ',
    yourPhone: 'ਤੁਹਾਡਾ ਫੋਨ',
    subject: 'ਵਿਸ਼ਾ',
    message: 'ਸੁਨੇਹਾ',
    remove: 'ਹਟਾਓ',
    subtotal: 'ਉਪ-ਕੁੱਲ',
    shipping: 'ਸ਼ਿਪਿੰਗ',
    calculated: 'ਚੈੱਕਆਊਟ ਤੇ ਗਣਨਾ',
    iphoneParts: 'ਆਈਫੋਨ ਪਾਰਟਸ',
    samsungParts: 'ਸੈਮਸੰਗ ਪਾਰਟਸ',
    xiaomiParts: 'ਸ਼ਾਓਮੀ ਪਾਰਟਸ',
    oppoRenoParts: 'ਓਪੋ ਰੀਨੋ ਪਾਰਟਸ',
    realmeParts: 'ਰੀਅਲਮੀ ਪਾਰਟਸ',
    huaweiParts: 'ਹੁਆਵੇਈ ਪਾਰਟਸ',
    onePlusParts: 'ਵਨਪਲੱਸ ਪਾਰਟਸ',
    motorolaParts: 'ਮੋਟੋਰੋਲਾ ਪਾਰਟਸ',
    alcatelParts: 'ਅਲਕਾਟੇਲ ਪਾਰਟਸ',
    tclParts: 'ਟੀਸੀਐਲ ਪਾਰਟਸ',
    zteParts: 'ਜ਼ੈਡਟੀਈ ਪਾਰਟਸ',
    vivoParts: 'ਵੀਵੋ ਪਾਰਟਸ',
    nokiaParts: 'ਨੋਕੀਆ ਪਾਰਟਸ',
    googlePixelParts: 'ਗੂਗਲ ਪਿਕਸਲ ਪਾਰਟਸ',
    tablets: 'ਟੈਬਲੇਟ',
    lgParts: 'ਐਲਜੀ ਪਾਰਟਸ',
    otherParts: 'ਹੋਰ ਪਾਰਟਸ',
    repairTools: 'ਮੁਰੰਮਤ ਔਜ਼ਾਰ',
    shopNow: 'ਹੁਣੇ ਖਰੀਦੋ',
    discoverMore: 'ਹੋਰ ਖੋਜੋ',
    newsletter: 'ਨਿਊਜ਼ਲੈਟਰ',
    newsletterDesc: 'ਨਵੀਨਤਮ ਅੱਪਡੇਟ ਲਈ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
    subscribe: 'ਸਬਸਕ੍ਰਾਈਬ',
    enterEmail: 'ਆਪਣੀ ਈਮੇਲ ਦਾਖਲ ਕਰੋ',
    quickLinks: 'ਤੇਜ਼ ਲਿੰਕ',
    aboutUs: 'ਸਾਡੇ ਬਾਰੇ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    termsConditions: 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
    faq: 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
    contactInfo: 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
    address: 'ਪਤਾ',
    phone: 'ਫੋਨ',
    email: 'ਈਮੇਲ',
    followUs: 'ਸਾਨੂੰ ਫਾਲੋ ਕਰੋ',
    allRightsReserved: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ',
    filterBy: 'ਫਿਲਟਰ ਕਰੋ',
    sortBy: 'ਕ੍ਰਮਬੱਧ ਕਰੋ',
    priceRange: 'ਕੀਮਤ ਦੀ ਸੀਮਾ',
    categories: 'ਸ਼੍ਰੇਣੀਆਂ',
    inStock: 'ਸਟਾਕ ਵਿੱਚ',
    outOfStock: 'ਸਟਾਕ ਵਿੱਚ ਨਹੀਂ',
    sale: 'ਸੇਲ',
    new: 'ਨਵਾਂ',
    off: 'ਛੋਟ',
    heroTitle: 'ਪ੍ਰੀਮੀਅਮ ਮੋਬਾਈਲ ਪਾਰਟਸ ਅਤੇ ਸਹਾਇਕ ਉਪਕਰਣ',
    heroSubtitle: 'ਕੁਆਲਿਟੀ ਮੋਬਾਈਲ ਪਾਰਟਸ ਲਈ ਤੁਹਾਡੀ ਇੱਕੋ ਮੰਜ਼ਿਲ',
    exploreBrands: 'ਬ੍ਰਾਂਡ ਖੋਜੋ',
    viewAll: 'ਸਾਰੇ ਦੇਖੋ',
    topCategories: 'ਚੋਟੀ ਦੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    whyChooseUs: 'ਸਾਨੂੰ ਕਿਉਂ ਚੁਣੋ',
    qualityProducts: 'ਕੁਆਲਿਟੀ ਉਤਪਾਦ',
    qualityProductsDesc: 'ਸਾਰੇ ਉਤਪਾਦ ਟੈਸਟ ਅਤੇ ਤਸਦੀਕ ਕੀਤੇ ਹਨ',
    fastDelivery: 'ਤੇਜ਼ ਡਿਲੀਵਰੀ',
    fastDeliveryDesc: 'ਦੁਨੀਆ ਭਰ ਵਿੱਚ ਤੇਜ਼ ਅਤੇ ਭਰੋਸੇਮੰਦ ਸ਼ਿਪਿੰਗ',
    expertSupport: 'ਮਾਹਰ ਸਹਾਇਤਾ',
    expertSupportDesc: 'ਪੇਸ਼ੇਵਰਾਂ ਤੋਂ ਤਕਨੀਕੀ ਸਹਾਇਤਾ',
    competitivePrices: 'ਮੁਕਾਬਲੇਬਾਜ਼ ਕੀਮਤਾਂ',
    competitivePricesDesc: 'ਬਾਜ਼ਾਰ ਵਿੱਚ ਸਭ ਤੋਂ ਵਧੀਆ ਕੀਮਤਾਂ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    usersInformation: 'ਉਪਭੋਗਤਾ ਜਾਣਕਾਰੀ',
    subscriptions: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨਾਂ',
    paymentApprovals: 'ਭੁਗਤਾਨ ਮਨਜ਼ੂਰੀਆਂ',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || translations.en[key] || key
    },
    [language]
  )

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
