import type { Product } from '@/components/store-provider'

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max LCD Display Assembly',
    price: 189.99,
    originalPrice: 229.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'iphone',
    brand: '50TEK',
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 17,
    description: 'High-quality LCD display assembly for iPhone 15 Pro Max with touch screen digitizer.',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra Screen Replacement',
    price: 249.99,
    originalPrice: 299.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'samsung',
    brand: '50TEK',
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 17,
    description: 'Premium AMOLED screen replacement for Samsung Galaxy S24 Ultra.',
  },
  {
    id: '3',
    name: 'HOCO USB-C Fast Charging Cable 2m',
    price: 12.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    isNew: false,
    description: 'Durable USB-C to USB-C fast charging cable with braided nylon cover.',
  },
  {
    id: '4',
    name: 'Xiaomi 14 Pro Battery Replacement',
    price: 45.99,
    originalPrice: 59.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'xiaomi',
    brand: '50TEK',
    inStock: true,
    isSale: true,
    discount: 23,
    description: 'Original capacity battery replacement for Xiaomi 14 Pro.',
  },
  {
    id: '5',
    name: 'Professional Phone Repair Tool Kit 25-Piece',
    price: 34.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'repair-tools',
    brand: '50TEK',
    inStock: true,
    isNew: true,
    description: 'Complete 25-piece precision tool kit for smartphone repairs.',
  },
  {
    id: '6',
    name: 'HOCO Wireless Charging Pad 15W',
    price: 29.99,
    originalPrice: 39.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    isSale: true,
    discount: 25,
    description: 'Fast wireless charging pad compatible with Qi-enabled devices.',
  },
  {
    id: '7',
    name: 'OnePlus 12 Back Glass Cover',
    price: 24.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'oneplus',
    brand: '50TEK',
    inStock: true,
    description: 'Premium back glass replacement cover for OnePlus 12.',
  },
  {
    id: '8',
    name: 'Google Pixel 8 Pro Camera Module',
    price: 89.99,
    originalPrice: 109.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'google-pixel',
    brand: '50TEK',
    inStock: false,
    isSale: true,
    discount: 18,
    description: 'Replacement camera module for Google Pixel 8 Pro.',
  },
  {
    id: '9',
    name: 'HOCO Power Bank 20000mAh',
    price: 49.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    isNew: true,
    description: 'High-capacity power bank with fast charging support.',
  },
  {
    id: '10',
    name: 'Huawei P60 Pro LCD Screen',
    price: 179.99,
    originalPrice: 219.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'huawei',
    brand: '50TEK',
    inStock: true,
    isSale: true,
    discount: 18,
    description: 'Original quality LCD display for Huawei P60 Pro.',
  },
  {
    id: '11',
    name: 'HOCO Bluetooth Earbuds TWS',
    price: 39.99,
    originalPrice: 54.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    isSale: true,
    discount: 27,
    description: 'True wireless stereo earbuds with active noise cancellation.',
  },
  {
    id: '12',
    name: 'Oppo Reno 10 Pro Charging Port Flex',
    price: 15.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'oppo-reno',
    brand: '50TEK',
    inStock: true,
    description: 'Charging port flex cable for Oppo Reno 10 Pro.',
  },
  {
    id: '13',
    name: 'Realme GT 5 Pro Screen Protector (3-Pack)',
    price: 9.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'realme',
    brand: 'HOCO',
    inStock: true,
    description: 'Tempered glass screen protector pack for Realme GT 5 Pro.',
  },
  {
    id: '14',
    name: 'Motorola Edge 40 Pro Battery',
    price: 42.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'motorola',
    brand: '50TEK',
    inStock: true,
    description: 'High-capacity replacement battery for Motorola Edge 40 Pro.',
  },
  {
    id: '15',
    name: 'HOCO Car Phone Mount Wireless Charger',
    price: 34.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    isNew: true,
    description: 'Automatic clamping car mount with 15W wireless charging.',
  },
  {
    id: '16',
    name: 'Vivo X100 Pro Front Camera',
    price: 35.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'vivo',
    brand: '50TEK',
    inStock: true,
    description: 'Front-facing camera module for Vivo X100 Pro.',
  },
  {
    id: '17',
    name: 'Nokia G60 5G LCD Display',
    price: 69.99,
    originalPrice: 89.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'nokia',
    brand: '50TEK',
    inStock: true,
    isSale: true,
    discount: 22,
    description: 'LCD display assembly for Nokia G60 5G.',
  },
  {
    id: '18',
    name: 'TCL 40 SE Touch Screen Digitizer',
    price: 29.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'tcl',
    brand: '50TEK',
    inStock: true,
    description: 'Touch screen digitizer for TCL 40 SE.',
  },
  {
    id: '19',
    name: 'ZTE Blade V50 Battery Cover',
    price: 14.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'zte',
    brand: '50TEK',
    inStock: true,
    description: 'Back battery cover for ZTE Blade V50.',
  },
  {
    id: '20',
    name: 'Alcatel 3L (2021) Screen Assembly',
    price: 49.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'alcatel',
    brand: '50TEK',
    inStock: false,
    description: 'Complete screen assembly for Alcatel 3L (2021).',
  },
  {
    id: '21',
    name: 'LG Velvet 5G OLED Display',
    price: 159.99,
    originalPrice: 199.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'lg',
    brand: '50TEK',
    inStock: true,
    isSale: true,
    discount: 20,
    description: 'OLED display replacement for LG Velvet 5G.',
  },
  {
    id: '22',
    name: 'iPad Pro 12.9" LCD Assembly',
    price: 299.99,
    originalPrice: 349.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'tablets',
    brand: '50TEK',
    inStock: true,
    isSale: true,
    discount: 14,
    description: 'Premium LCD assembly for iPad Pro 12.9-inch.',
  },
  {
    id: '23',
    name: 'Heat Gun Station for Repairs',
    price: 79.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'repair-tools',
    brand: '50TEK',
    inStock: true,
    isNew: true,
    description: 'Professional-grade heat gun station for phone repairs.',
  },
  {
    id: '24',
    name: 'HOCO Laptop Stand Aluminum',
    price: 44.99,
    image: '/placeholder.svg?height=400&width=400',
    category: 'accessories',
    brand: 'HOCO',
    inStock: true,
    description: 'Ergonomic aluminum laptop stand with adjustable height.',
  },
]

export const categories = [
  { key: 'iphoneParts', slug: 'iphone', count: 45 },
  { key: 'samsungParts', slug: 'samsung', count: 38 },
  { key: 'xiaomiParts', slug: 'xiaomi', count: 32 },
  { key: 'oppoRenoParts', slug: 'oppo-reno', count: 18 },
  { key: 'realmeParts', slug: 'realme', count: 15 },
  { key: 'huaweiParts', slug: 'huawei', count: 28 },
  { key: 'onePlusParts', slug: 'oneplus', count: 22 },
  { key: 'motorolaParts', slug: 'motorola', count: 12 },
  { key: 'alcatelParts', slug: 'alcatel', count: 8 },
  { key: 'tclParts', slug: 'tcl', count: 10 },
  { key: 'zteParts', slug: 'zte', count: 9 },
  { key: 'vivoParts', slug: 'vivo', count: 16 },
  { key: 'nokiaParts', slug: 'nokia', count: 14 },
  { key: 'googlePixelParts', slug: 'google-pixel', count: 20 },
  { key: 'tablets', slug: 'tablets', count: 25 },
  { key: 'lgParts', slug: 'lg', count: 11 },
  { key: 'otherParts', slug: 'other', count: 30 },
  { key: 'repairTools', slug: 'repair-tools', count: 42 },
]

export function getProductsByCategory(category: string): Product[] {
  return sampleProducts.filter((p) => p.category === category)
}

export function getProductsByBrand(brand: string): Product[] {
  return sampleProducts.filter((p) => p.brand?.toLowerCase() === brand.toLowerCase())
}

export function getFeaturedProducts(): Product[] {
  return sampleProducts.filter((p) => p.isNew || p.isSale).slice(0, 8)
}

export function getNewArrivals(): Product[] {
  return sampleProducts.filter((p) => p.isNew)
}

export function getSaleProducts(): Product[] {
  return sampleProducts.filter((p) => p.isSale)
}
